 services:
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432  # enables connecting locally via psql
    environment:
      POSTGRES_DB: comments
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_HOST_AUTH_METHOD: trust